#!/bin/bash
# Sucht aus einer vorbereiteten LDIF-Datei fuer die fetchmail- und Postfix-Eintraege
# des invis-Servers im LDAP (AD) alle Benutzer hereua und legt fuer diese Unterknoten
# im AD an.
# Nuetzlich bei der Migration von invis-Classic auf invis-AD

# (c) 2016 Stefan Schaefer - invis-server.org

# License: GPLv3
# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 


cornazbase="CN=AdditionalUserInformation,CN=invis-server,DC=pe,DC=loc"
filename=$1

users=(`cat $filename |grep "fspLocalMailAddress:" |cut -d " " -f 2 |cut -d "@" -f1|sort -u`)

for user in ${users[*]}; do 
    
    # DN erstellen
    dn="dn: CN=$user,$cornazbase"
    
    # Anzahl der Zeichen im DN zählen
    dncount=`echo $dn | wc -c`
    
    # DN zerlegen, wenn laenger als 79 Zeichen
    if (( $dncount > 79 )); then
	dn1=`echo $dn|cut -c 1-79`
	dn2=`echo $dn|cut -c 80-`
	echo "$dn1"
	if [[ -n $dn2 ]]; then
	    echo " $dn2"
	fi
    else
	echo "$dn"
    fi
    
    #LDIF ergaenzen
	echo "cn: $user"
	echo "description: Email-Konten von $user"
	echo "name: $user"
	echo "objectclass: top"
	echo "objectclass: container"
	echo
done
