#!/bin/bash
# Script zum veraendern von IP-Adressbereichen des invis-Servers
# (c) 2016 Stefan Schaefer - invis-server.org

# License: GPLv3
# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 


datei="./ptr-liste-hosts1.txt"

for ip in `cat $datei |cut -d "." -f4 |cut -d "," -f1`; do
    ((newip=$ip-99))
    # Arg2 = Datei, Arg3 = sed String
    cat $datei|sed "s%.$ip%.$newip%g" > $datei.new
    mv $datei.new $datei
done
