#!/bin/bash
# Script zum Einfuegen vieler DNS Eintraege anhand einer Liste
# (c) 2016 Stefan Schaefer - invis-server.org

# License: GPLv3
# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 

liste="$1"
zone="16.172.in-addr.arpa"
server="localhost"
user="Administrator"
pw="p@ssw0rd"
type="PTR"

for entry in `cat $liste`; do
    #samba-tool dns add <server> <zone> <name> <A|AAAA|PTR|CNAME|NS|MX|SRV|TXT> <data>
    if [[ $type == "PTR" ]]; then
	name=`echo $entry |cut -d "," -f1 | cut -d "." -f3-4`
	name1=`echo $name |cut -d "." -f2`
	name2=`echo $name |cut -d "." -f1`
	data=`echo $entry |cut -d "," -f2`
	samba-tool dns add $server $zone $name1.$name2 $type "$data." -U $user --password=$pw
    elif [[ $type == "A" ]]; then
	name=`echo $entry |cut -d "," -f2 | cut -d "." -f1`
	data=`echo $entry |cut -d "," -f1`
	samba-tool dns add $server $zone $name $type $data -U $user --password=$pw
    fi
done
