#!/bin/bash
# Minimale openSUSE Leap Installation fuer invis Server Setup vorbereiten

# (c) 2015 Stefan Schaefer - invis-server.org

# License: GPLv3
# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 

# System vorbereiten, yast installieren
zypper -n rm -t pattern minimal_base-conflicts
zypper -n in -t pattern yast2_basis

# Invis-Repo installieren
while [[ ! $iversion =~ [s,u] ]]; do
	read -p "Soll eine 'stable' oder 'unstable' Version des invis-Servers installiert werden? (s,u) " iversion
	iversion=`echo $iversion | tr [:upper:] [:lower:]`
done

if [[ $iversion == s ]]; then
	zypper ar -f http://download.opensuse.org/repositories/spins:/invis:/stable/openSUSE_42.1/spins:invis:stable.repo
else
	zypper ar -f http://download.opensuse.org/repositories/spins:/invis:/unstable/openSUSE_42.1/spins:invis:unstable.repo
fi

zypper --gpg-auto-import-keys ref

