#!/bin/bash
# Script zur Vorbereitung des invis-Server Setups
# invis-Server 11/12

# (c) 2015,2016 Stefan Schaefer - invis-server.org

# License: GPLv3
# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 

# Invis-Repo installieren
while [[ ! $iversion =~ [s,u] ]]; do
	read -p "Soll eine 'stable' oder 'unstable' Version des invis-Servers installiert werden? (s,u) " iversion
	iversion=`echo $iversion | tr [:upper:] [:lower:]`
done
# SUSE Release ermitteln - fuer unstable Installation
suseversion=`cat /etc/SuSE-release | grep VERSION |tr -d " " |cut -d "=" -f2`

if [[ $iversion == s ]]; then
	zypper ar -f http://download.opensuse.org/repositories/spins:/invis:/stable/openSUSE_Leap_42.2/spins:invis:stable.repo
	zypper ar -f http://download.opensuse.org/repositories/spins:/invis:/stable:/samba/openSUSE_42.2/spins:invis:stable:samba.repo
else
	zypper ar -f http://download.opensuse.org/repositories/spins:/invis:/unstable/openSUSE_Leap_$suseversion/spins:invis:unstable.repo
	zypper ar -f http://download.opensuse.org/repositories/spins:/invis:/unstable:/samba/openSUSE_Leap_$suseversion/spins:invis:unstable:samba.repo
fi

# Repository-Schluessel importieren
zypper --gpg-auto-import-keys ref

