#!/bin/bash

# Script zum Erstellen eines neuen tarballs

# (c) 2018 Ingo Göppert - invis-server.org

# License: GPLv3
# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 


# Neue Versionsnummer setzen
VERSION=2.4.0

# Alten Kram löschen, neu clonen und Verzeichnisstruktur für das tar vorbereiten
rm -r -f z-push*
git clone -b $VERSION https://stash.z-hub.io/scm/zp/z-push.git z-push-$VERSION/
cd z-push-$VERSION
sed -s "s/ZPUSHVERSION/$VERSION/" build/version.php.in > src/version.php
rm -r -f .git0
rm -r -f build
rm -r -f man
rm -r -f config
rm -f src/.gitignore
rm *.*
mv src/* .
rm -r -f src

# neues tar erstellen
cd ..
tar -czf z-push-$VERSION.tar.gz z-push-$VERSION
