# Erweiterungen der Apache Konfiguration für invis Server
# Auch die Hauptseite läuft als namensbasierter virtueller Host.
# (C) 2010-2017 invis-server.org
# Author: Stefan Schaefer -- stefan@invis-server.org
# Questions: http://forum.invis-server.org 

# Virtual Host Definition
<VirtualHost 192.168.220.10:80>
    ServerAdmin	domadmin@invis-net.loc
    ServerName	invisX.invis-net.loc
    DocumentRoot /srv/www/htdocs/portal
    ErrorLog /var/log/apache2/vh-intern-error.log
    CustomLog /var/log/apache2/vh-intern-access.log combined

    # Aliasnamen für Elemente ausserhalb des Portalverzeichnisses
    Alias /cornaz /srv/www/htdocs/cornaz
    # Alias /phpldapadmin /srv/www/htdocs/phpldapadmin/public
    # Alias /phpMyAdmin /srv/www/htdocs/phpMyAdmin
    # Alias /phpPgAdmin /srv/www/htdocs/phpPgAdmin


    <IfDefine PHPVB>
	<Location /phpvirtualbox>
	    # Apache 2.x
	    <IfModule !mod_authz_core.c>
                Order allow,deny
                Deny from all
	    </IfModule>
	    # Apache 2.4
	    <IfModule mod_authz_core.c>
                Require all denied
	    </IfModule>
	</Location>
    </IfDefine>
    
    <Location /phpldapadmin>
        # Apache 2.x
        <IfModule !mod_authz_core.c>
                Order allow,deny
                Deny from all
        </IfModule>
        # Apache 2.4
        <IfModule mod_authz_core.c>
                Require all denied
        </IfModule>
    </Location>

</VirtualHost>

# interner Zugriff via SSL
<IfModule mod_ssl.c>
    <VirtualHost *:443>
	ServerAdmin	domadmin@invis-net.loc
	ServerName	invisX.invis-net.loc
	DocumentRoot /srv/www/htdocs/portal
	ErrorLog /var/log/apache2/vh-intern-ssl-error.log
	CustomLog /var/log/apache2/vh-intern-ssl-access.log ssl_combined

	SSLEngine On
	SSLCertificateFile /etc/apache2/ssl.crt/invis-sslint.crt
	SSLCertificateKeyFile /etc/apache2/ssl.key/invis-sslint.key

	# Aliasnamen für Elemente ausserhalb des Portalverzeichnisses
	Alias /cornaz /srv/www/htdocs/cornaz
	Alias /phpldapadmin /srv/www/htdocs/phpldapadmin

	<IfDefine PHPVB>
	    Alias /vbphp /srv/www/htdocs/phpvirtualbox
	</IfDefine>

	<IfDefine DOKUWIKI>
	    Alias /dokuwiki /srv/www/htdocs/dokuwiki
	</IfDefine>

    </VirtualHost>
</IfModule>
