#!/bin/bash
# Kategorie: server
# bootpartition sichern, soweit vorhanden
# (c) 2013 Stefan Schaefer -- invis-server.org
# Mail: stefan@invis-server.org

# License: GPLv3
# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 

# Konfigurationsdaten
conffile="/etc/invis/invis.conf"
passfile="/etc/invis/invis-pws.conf"

# Funktionen
# Werte aus Konfigurationsdatendatei extrahieren
# $1 = Konfigurationsdatei, $2 = Parameter, $3 Wert (Feld)
getconfdata() {
    cat $1 |grep "$2" | cut -d ":" -f $3
}

## Sicherungsverzeichnis

dasibase=`getconfdata $conffile "DasiDir" "2"`
dasidir="$dasibase/bootpartition"

if [[ ! -d $dasidir ]]; then
    mkdir -p $dasidir
fi

bootpart=`mount | grep "/boot "| cut -d " " -f1`
datum=`date +%Y%m%d`

if [[ -n $bootpart ]]; then
    echo "Ein Image der Bootpartition wird angelegt"
    dd if=$bootpart of=$dasidir/bootpart-$datum.img
fi

