#!/bin/bash
# Script zur Prüfung des Samba Logfiles auf bestimmte Ereignisse
# (C) 2013 Ingo Göppert
# License: GPLv3
# Version: 2.0

checkusername() {
  # Log durchsuchen
  if [ -f "$loginfile" ]; then
    grep -B 1 "$username" "$loginfile" >> "$logoutdir/$username"
    delete_logfile=1
  fi
}

# Global
loginfile="/var/log/samba/log.smbd.old"
logoutdir="/var/log/samba"
delete_logfile=0

# Lokal
username="vorname.nachname"
checkusername

# Ende
if (( $delete_logfile == 1 )); then
    rm "$loginfile"
fi

exit 0
