#!/bin/bash
# Zarafa-Attribut in AD Benutzerkonten aktivieren
#
# (C) 2016 Stefan Schäfer - invis-server.org

# License: GPLv3
# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 



userbase="CN=Users,DC=pe,DC=loc"
userlist="./zarafa-userlist.txt"
grouplist="./zarafa-grouplist.txt"
sam="/var/lib/samba/private/sam.ldb"
workfile="/tmp/addzactive"

funktion=$1

case $funktion in
    "othermail")
	    echo "otherMailbox Adresse tauschen"
	    for user in `cat $userlist`; do
	    
		# DN ermitteln
		dn=`ldbsearch -H /var/lib/samba/private/sam.ldb "(samaccountname=$user)" dn |grep ^dn:`
		echo $dn
		echo "$dn" > $workfile
		echo "changetype: modify" >> $workfile
		echo "add: otherMailbox" >> $workfile
		echo "otherMailbox: $user@pe.loc" >> $workfile
		#cat $workfile
		ldbmodify -H $sam $workfile
	    done
	    exit
	    ;;

    "actuser")
	    echo "Benutzer aktivieren"
	    for user in `cat $userlist`; do
	    
		# DN ermitteln
		dn=`ldbsearch -H /var/lib/samba/private/sam.ldb "(samaccountname=$user)" dn |grep ^dn:`
		echo $dn
		echo "$dn" > $workfile
		echo "changetype: modify" >> $workfile
		echo "add: zarafaAccount" >> $workfile
		echo "zarafaAccount: 1" >> $workfile
		#cat $workfile
		#ldbmodify -H $sam $workfile
	    done
	    exit
	    ;;
    "actgroup")
	    echo "Gruppen aktivieren"
	    for group in `cat $grouplist`; do
		echo "dn: CN=$group,$userbase" > $workfile
		echo "changetype: modify" >> $workfile
		echo "add: zarafaAccount" >> $workfile
		echo "zarafaAccount: 1" >> $workfile
		#ldbmodify -H $sam $workfile
	    done
	    exit
	    ;;
    *)
	    echo "Usage:"
	    echo "addzactive [actuser|actgroup|othermail]"
	    ;;
esac
