#!/bin/bash
# Script to control all zarafa services together
# This script is using systemctl!
# (c) 2016 Stefan Schaefer - stefan@invis-server.org
# License: GPLv3

services=(licensed server search spooler dagent gateway ical monitor)

case "$1" in
    start)
	for service in ${services[*]}; do
	    systemctl start zarafa-$service.service
	done
	;;
    stop)
	for service in `echo ${services[*]} | tr " " '\n' |tac`; do
	    systemctl stop zarafa-$service.service
	done
	;;
    status)
	for service in ${services[*]}; do
	    systemctl status zarafa-$service.service
	done
	;;
    *)
	echo "Usage: runzarafa {start|stop|status}"
	;;
esac
