#!/bin/bash
### MODUL-NR. 018 ###
# (c) August 2008 Stefan Schäfer / FSP Computer & Netzwerke
# (c) 2009-2017 Stefan Schäfer / invis-server.org / stefan@invis-server.org
# (c) 2013,2014 Dimitri Asarowski / invis-server.org / dimitri@invis-server.org
# (c) 2013-2017 Ingo Göppert / invis-server.org / ingo@invis-server.org

# License: GPLv3
# Questions: info@invis-server.org

# ERP Software Installation

# ERP software setup

# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# include functions
source $SINEINCLUDEDIR/functions

modulename=`basename $0`

clear
windowtitle="ERP Setup"
pgsubtitle="Kivitendo - WaWision"

whicherp=`getconfdata "ERPSoftware" "2"`
case $whicherp in

    "invoiceplane")
	windowtitle="InvoicePlane Installation"
	dialog --backtitle "$DIALOGTITLE - Modul: $modulename" --title "$windowtitle"  --exit-label "Weiter" --textbox "$INFODIR/invoiceplane.txt" 20 90 --and-widget --backtitle "$DIALOGTITLE - Modul: $modulename" --title "$windowtitle"  --defaultno --yesno "Möchten Sie InvoicePlane installieren?" 0 0
	cont=${?}
	
	if [[ $cont == "0" ]]; then
	    pgsubtitle="Zusätzliche Software wird installiert"
	    zypper refresh 2>&1 | tee -a $LOGFILE  |pgbox
	    zypper -n install -n invoiceplane 2>&1 |pgbox
	    zyppercheck ${PIPESTATUS[0]}
	    # Hier Datenbank installation einfügen
	    ippass=`mkdbsilent invoiceplane ip a`
	    echo "DB-User ip:IPDBPASS:$ippass" >> $SINEWORKINGDIR/invis_pws 

	    # Konfiguration anpassen
	    fqdn=`getconfdata "FQDN" "2"`
	    file=ipconfig.php
	    path="/etc/invoiceplane"
	    string="IP_URL=%IP_URL=https://$fqdn/invoiceplane"
	    changevalues $path $file "$string"
	    chown .www $path/$file
	    chmod g+w $path/$file
	    a2enflag INVOICEPLANE
	
	    chkservice apache2 r
	    # InvoicePlane im Portal aktivieren
	    swpestat InvoicePlane TRUE 2>&1 | tee -a $LOGFILE | pgbox

	else
	    msgbox "InvoicePlane Installation übersprungenen" "$windowtitle"
	fi
	;;

    *)
        msgbox "Keine ERP Software gewünscht" "$windowtitle"
	;;
esac
