#!/bin/bash
### MODUL-NR. 022 ###
# (c) August 2008 Stefan Schäfer / FSP Computer & Netzwerke
# (c) 2009-2017 Stefan Schäfer / invis-server.org / stefan@invis-server.org
# (c) 2013,2014 Dimitri Asarowski / invis-server.org / dimitri@invis-server.org
# (c) 2013-2017 Ingo Göppert / invis-server.org / ingo@invis-server.org

# License: GPLv3
# Questions: info@invis-server.org

# Kimai Installation

# Kimai setup

# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# include functions
source $SINEINCLUDEDIR/functions

modulename=`basename $0`

clear
windowtitle="Kimai"
pgsubtitle="Kimai Arbeitszeiterfassung installieren"

dialog --backtitle "$DIALOGTITLE - Modul: $modulename" --title "$windowtitle" --exit-label "Weiter" --textbox "$INFODIR/kimai.txt" 0 0 --and-widget --backtitle "$DIALOGTITLE" --title "$windowtitle"  --defaultno --yesno "Möchten Sie Kimai installieren?" 0 0
cont=${?}

# Weitermachen?
if [[ $cont == "0" ]]; then
    pgsubtitle="Software wird installiert"
    zypper refresh 2>&1 | tee -a $LOGFILE | pgbox
    zypper -n install kimai 2>&1 | tee -a $LOGFILE | pgbox
    zyppercheck ${PIPESTATUS[0]}
    # Hier Datenbank installation einfügen
    kimaipass=`mkdbsilent kimai kimai a`

    msgbox "Datenbank für Kimai wurde angelegt.\n\nDatenbank: kimai\nBenutzer: kimai\nPasswort: $kimaipass\n\nNotieren Sie sich bitte diese Daten. Sie werden beim ersten Zugriff auf Kimai benötigt." "$windowtitle"

    # activate apache configuration
    cp $TEMPLATEDIR/$modulename/kimai.conf /etc/apache2/conf.d

    fqdn=`getconfdata "FQDN" "2"`
    basedn=`getconfdata "baseDN" "2"`
    ldapmasterpw=`getconfdata "LDAPAdminPW" "2"`

    # add and modify activeDirectory configuration
    path="/srv/www/htdocs/kimai/includes"
    file="auth.php"
    cp $TEMPLATEDIR/$modulename/$file $path

    string="invis.invis-net.loc%$fqdn"
    changevalues $path $file "$string"

    string="DC=invis-net,DC=loc%$basedn"
    changevalues $path $file "$string"

    string="ldapadminpw%$ldapmasterpw"
    changevalues $path $file "$string"

    # set KIMAI flag
    a2enflag KIMAI
    chkservice apache2 r

    # ownCloud im Portal aktivieren
    swpestat Kimai TRUE 2>&1 | tee -a $LOGFILE | pgbox

else
    msgbox "Kimai Installation übersprungen" "$windowtitle"
fi
